### PR TITLE
VR Process Filter

### PR DESCRIPTION
**Pull request by NoobCat-xxd**

### CODE REVIEW

**Comment by Mantas-2155X** [comment]
Hello, thanks for the PR.

Since I don't have VR, I can't test anything.. does this work fine with the extra UI? There are no glitches and just letting it run in VR is fine?

**Comment by hujihiji** [comment]
HCharaSwitcher is not displayed in vr, so I think that there is no problem if you run it in vr.

**Comment by Mantas-2155X** [comment]
as I've received DMs claiming that this doesn't work properly even with the change, I need full confirmation of this working.

**Comment by Mantas-2155X** [comment]
Closed for now. Reopen if you get it actually working in VR

**Comment by Mantas-2155X** [comment]
The official VR compatible version of the plugin has been released, please check it out.

**Pull request closed without merging**
